### ISSUE TITLE
bundle import fail

### ISSUE THREAD

**Issue by spheras** [nylnook/nylnook-krita-brushes#1]
Hello! when I try to import the bundle from my krita (v 2.9.10) it says (in spanish) "Las sumas MD5 de los siguientes recursos han resultado discordantes. Es posible que se hayan dañado, por ejemplo, durante la descarga. Nylnook Block & Mix" ... what basically means  "MD5 checksums of the  following resources have been discordant. You may have been damaged, for example, during unloading."  
I've tried downloading 2 or 3 times again, but nothing changes. 

the downloaded bundle file is 959,9 kB, my SO is an elementary distribution (64bits)
I'm currently working with the last deevad bundle version without problems. That's the only bundle i've imported previously.

Hope this info helps. Tell me if I can help. Thanks!

**Comment by nylnook** [comment]
Hello @spheras !
Sorry you run into troubles, and thanks for your report...
I don't know what caused this issue... it's possible an error occurred during my export. In doubt, I just exported it again minutes ago, and updated the download link. 

So... this should work now... Please try again and let me know if this is working for you !

Thanks to you ;)

**Comment by nylnook** [comment]
After a second check, textures were missing... so I just released v1.1 ;)

**Comment by spheras** [comment]
Great! thank you very much, now it works, I can import the bundle successfully.  I will test them this evening, thank you again.

Just one thing: the following brushes appears with an X at the right (not sure if this is normal):

Nylnook Airbrush
Nylnook Ink Dirty
Nylnook Ink Power Bear Paw
Nylnook Ink Power Triangle

I attach a capture of some.
![capture](https://cloud.githubusercontent.com/assets/3862933/12230211/ed0ed784-b84e-11e5-8abd-4de87c3aac5e.png)

**Comment by spheras** [comment]
Oh, comments crossed :D
after the version  v1.1, only the "Nylnook Airbrush" have a cross in the right

**Comment by nylnook** [comment]
Arg !
Updated again with the same 1.1 tag... this texture in particular was in another Bundle (Cazu)... so for some reason it wasn't included.

Should work now ! Thanks you for testing !
And please let me know what do think about theses brushes ;)

**Comment by spheras** [comment]
Yeah, now it seems perfectly imported. Thank you very much @nylnook .
Sure! I will let you know my opinion (hope to find time to check these brushes during these days). In any case, I'm not a professional, just trying to learn digital painting :D, but any contribution to the open source world is always good news.

thanks!

**Comment by nylnook** [comment]
Good news it works ;) 
You're welcome !
